name: Android CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build Debug APK
              run: ./gradlew assembleDebug --no-daemon

            - name: Run unit tests
              run: ./gradlew test --no-daemon
